jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        COMMIT_FILTER: '[skip ci]'
      if: contains(github.event.head_commit.message, '[skip ci]')
      name: Check Commit Message [skip CI]
      run: 'echo "no ''skip ci'' in commit message"

        exit 2

        '
    - continue-on-error: true
      id: regex-match
      uses: actions-ecosystem/action-regex-match@v2
      with:
        regex: '[^\x00-\x7F]+'
        text: ${{ github.event.head_commit.message }}
    - continue-on-error: true
      if: ${{ steps.regex-match.outputs.match != '' }}
      name: Check Commit Message [Non-ASCII]
      run: 'echo "No Non-ASCII msg in commit message"

        exit 2

        '
name: Commit Message Check
on:
  repository_dispatch:
    types: trigger-ga___check_commit_message.yml
