jobs:
  clear-ccache:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clear cache
      uses: actions/github-script@v7
      with:
        script: "console.log(\"About to clear\")\nconst caches = await github.rest.actions.getActionsCacheList({\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n})\nfor (const\
          \ cache of caches.data.actions_caches) {\n  console.log(cache)\n  github.rest.actions.deleteActionsCacheById({\n\
          \    owner: context.repo.owner,\n    repo: context.repo.repo,\n    cache_id:\
          \ cache.id,\n  })\n}\nconsole.log(\"Clear completed\")\n"
name: Clear cache
on:
  repository_dispatch:
    types: trigger-ga___clean.yml
permissions:
  actions: write
